import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../core/services/firestore_service.dart';
import '../core/services/storage_service.dart';
import '../core/constants/firestore_paths.dart';
import '../core/utils/media_compressor.dart';
import '../core/enums/message_type.dart';
import '../core/enums/message_status.dart';
import '../models/message.dart';

/// Holds before/after compression stats for the UI to display.
class CompressionResult {
  final double originalMb;
  final double compressedMb;
  final String type;

  CompressionResult({
    required this.originalMb,
    required this.compressedMb,
    required this.type,
  });

  double get savingsPercent =>
      ((originalMb - compressedMb) / originalMb * 100).clamp(0, 100);

  String get summary =>
      '${type == "image" ? "📷" : "🎬"} '
      '${originalMb.toStringAsFixed(2)} MB → '
      '${compressedMb.toStringAsFixed(2)} MB '
      '(${savingsPercent.toStringAsFixed(0)}% smaller)';
}

class ChatViewModel extends ChangeNotifier {
  final String conversationId;
  final FirestoreService _firestoreService = FirestoreService();
  final String? _currentUserId = FirebaseAuth.instance.currentUser?.uid;
  final ScrollController scrollController = ScrollController();

  StreamSubscription? _messagesSubscription;
  Timer? _typingDebounce;
  Timer? _idleTimer;

  bool _isTyping = false;
  double? _mediaUploadProgress;
  CompressionResult? _lastCompression;

  double? get mediaUploadProgress => _mediaUploadProgress;
  CompressionResult? get lastCompression => _lastCompression;

  ChatViewModel(this.conversationId) {
    // Optional: could initialize listeners here if needed
  }

  Stream<QuerySnapshot> get messagesStream {
    return _firestoreService.getMessages(conversationId);
  }

  Stream<DocumentSnapshot> get conversationStream {
    return FirebaseFirestore.instance
        .collection('conversations')
        .doc(conversationId)
        .snapshots();
  }

  void onTextChanged(String text) {
    if (_currentUserId == null) return;

    if (_typingDebounce?.isActive ?? false) _typingDebounce!.cancel();

    if (!_isTyping && text.isNotEmpty) {
      _isTyping = true;
      _firestoreService.updateTypingStatus(
        conversationId,
        _currentUserId,
        true,
      );
    }

    if (text.isEmpty) {
      _clearTypingStatus();
      return;
    }

    _typingDebounce = Timer(const Duration(milliseconds: 1000), () {
      // Debounce logic - reset idle timer
      _idleTimer?.cancel();
      _idleTimer = Timer(const Duration(seconds: 2), () {
        _clearTypingStatus();
      });
    });
  }

  void _clearTypingStatus() {
    if (_currentUserId == null || !_isTyping) return;
    _isTyping = false;
    _firestoreService.updateTypingStatus(conversationId, _currentUserId, false);
  }

  Future<void> sendTextMessage(String text) async {
    final uid = _currentUserId;
    if (uid == null || text.trim().isEmpty) return;

    final timestamp = Timestamp.now();
    final message = Message(
      id: '', // Will be generated by Firestore
      senderId: uid,
      text: text.trim(),
      type: MessageType.text,
      reactions: {},
      status: MessageStatus.sending, // Optimistic UI
      readBy: {},
      deletedFor: [],
      deletedForEveryone: false,
      createdAt: timestamp,
    );

    try {
      _clearTypingStatus(); // Clear typing status immediately on send

      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
        conversationId,
        text.trim(),
        timestamp,
      );
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending message: $e');
    }
  }

  Future<void> sendAudioMessage(String filePath, int durationSeconds) async {
    final uid = _currentUserId;
    if (uid == null) return;

    try {
      final file = File(filePath);
      final url = await StorageService().uploadAudio(file);
      final timestamp = Timestamp.now();
      final message = Message(
        id: '',
        senderId: uid,
        type: MessageType.audio,
        mediaUrl: url,
        duration: durationSeconds,
        reactions: {},
        status: MessageStatus.sent,
        readBy: {},
        deletedFor: [],
        deletedForEveryone: false,
        createdAt: timestamp,
      );
      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
          conversationId, '🎤 Voice message', timestamp);
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending audio: $e');
    }
  }

  Future<void> sendMediaMessage(File file, String type) async {
    final uid = _currentUserId;
    if (uid == null) return;

    _mediaUploadProgress = 0.0;
    notifyListeners();

    try {
      // Measure original size
      final originalBytes = await file.length();
      final originalMb = originalBytes / (1024 * 1024);

      // Compress before upload
      File compressed;
      if (type == 'image') {
        compressed = await MediaCompressor.compressImage(file);
      } else {
        compressed = await MediaCompressor.compressVideo(file);
      }

      // Measure compressed size and expose to UI
      final compressedBytes = await compressed.length();
      final compressedMb = compressedBytes / (1024 * 1024);
      _lastCompression = CompressionResult(
        originalMb: originalMb,
        compressedMb: compressedMb,
        type: type,
      );
      notifyListeners();

      final url = await StorageService().uploadMedia(
        compressed,
        type == 'image' ? 'images' : 'videos',
        onProgress: (p) {
          _mediaUploadProgress = p;
          notifyListeners();
        },
      );

      final cleanUrl = StorageService.cleanUrl(url);
      final timestamp = Timestamp.now();
      final preview = type == 'image' ? '📷 Photo' : '🎬 Video';

      final message = Message(
        id: '',
        senderId: uid,
        type: type == 'image' ? MessageType.image : MessageType.video,
        mediaUrl: cleanUrl,
        reactions: {},
        status: MessageStatus.sent,
        readBy: {},
        deletedFor: [],
        deletedForEveryone: false,
        createdAt: timestamp,
      );

      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
          conversationId, preview, timestamp);
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending media: $e');
    } finally {
      _mediaUploadProgress = null;
      notifyListeners();
    }
  }

  Future<void> toggleReaction(String messageId, String emoji) async {
    final uid = _currentUserId;
    if (uid == null) return;

    try {
      // We need to read the current reactions for this message to toggle properly
      final msgDoc = await FirebaseFirestore.instance
          .collection(FirestorePaths.conversations)
          .doc(conversationId)
          .collection(FirestorePaths.messages)
          .doc(messageId)
          .get();

      if (!msgDoc.exists) return;

      final reactions = Map<String, String>.from(
        msgDoc.data()?['reactions'] ?? {},
      );
      final currentReaction = reactions[uid];

      if (currentReaction == emoji) {
        // Remove reaction
        await _firestoreService.updateMessageReaction(
          conversationId,
          messageId,
          uid,
          null,
        );
      } else {
        // Add or change reaction
        await _firestoreService.updateMessageReaction(
          conversationId,
          messageId,
          uid,
          emoji,
        );
      }
    } catch (e) {
      debugPrint('Error toggling reaction: $e');
    }
  }

  Future<void> markAsRead(String messageId, Map<String, dynamic> data) async {
    final uid = _currentUserId;
    if (uid == null) return;

    final senderId = data['senderId'] as String?;
    if (senderId == uid) return; // Don't mark our own messages as read

    final readBy = Map<String, dynamic>.from(data['readBy'] ?? {});
    if (readBy.containsKey(uid)) return; // Already marked as read by us

    try {
      await _firestoreService.markMessageAsRead(conversationId, messageId, uid);
    } catch (e) {
      debugPrint('Error marking as read: $e');
    }
  }

  void _scrollToBottom() {
    if (scrollController.hasClients) {
      scrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
    }
  }

  @override
  void dispose() {
    _messagesSubscription?.cancel();
    _typingDebounce?.cancel();
    _idleTimer?.cancel();
    _clearTypingStatus();
    scrollController.dispose();
    super.dispose();
  }
}
