import 'dart:async';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../core/services/firestore_service.dart';
import '../core/enums/message_type.dart';
import '../core/enums/message_status.dart';
import '../models/message.dart';

class ChatViewModel extends ChangeNotifier {
  final String conversationId;
  final FirestoreService _firestoreService = FirestoreService();
  final String? _currentUserId = FirebaseAuth.instance.currentUser?.uid;
  final ScrollController scrollController = ScrollController();
  
  StreamSubscription? _messagesSubscription;
  Timer? _typingDebounce;
  Timer? _idleTimer;

  bool _isTyping = false;

  ChatViewModel(this.conversationId) {
    // Optional: could initialize listeners here if needed
  }

  Stream<QuerySnapshot> get messagesStream {
    return _firestoreService.getMessages(conversationId);
  }

  Stream<DocumentSnapshot> get conversationStream {
    return FirebaseFirestore.instance.collection('conversations').doc(conversationId).snapshots();
  }

  void onTextChanged(String text) {
    if (_currentUserId == null) return;

    if (_typingDebounce?.isActive ?? false) _typingDebounce!.cancel();

    if (!_isTyping && text.isNotEmpty) {
      _isTyping = true;
      _firestoreService.updateTypingStatus(conversationId, _currentUserId!, true);
    }

    if (text.isEmpty) {
      _clearTypingStatus();
      return;
    }

    _typingDebounce = Timer(const Duration(milliseconds: 1000), () {
      // Debounce logic - reset idle timer
      _idleTimer?.cancel();
      _idleTimer = Timer(const Duration(seconds: 2), () {
        _clearTypingStatus();
      });
    });
  }

  void _clearTypingStatus() {
    if (_currentUserId == null || !_isTyping) return;
    _isTyping = false;
    _firestoreService.updateTypingStatus(conversationId, _currentUserId!, false);
  }

  Future<void> sendTextMessage(String text) async {
    final uid = _currentUserId;
    if (uid == null || text.trim().isEmpty) return;

    final timestamp = Timestamp.now();
    final message = Message(
      id: '', // Will be generated by Firestore
      senderId: uid,
      text: text.trim(),
      type: MessageType.text,
      reactions: {},
      status: MessageStatus.sending, // Optimistic UI
      readBy: {},
      deletedFor: [],
      deletedForEveryone: false,
      createdAt: timestamp,
    );

    try {
      _clearTypingStatus(); // Clear typing status immediately on send
      
      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
        conversationId, 
        text.trim(), 
        timestamp
      );
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending message: $e');
    }
  }

  void _scrollToBottom() {
    if (scrollController.hasClients) {
      scrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
    }
  }

  @override
  void dispose() {
    _messagesSubscription?.cancel();
    _typingDebounce?.cancel();
    _idleTimer?.cancel();
    _clearTypingStatus();
    scrollController.dispose();
    super.dispose();
  }
}
