import 'dart:async';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import '../core/services/firestore_service.dart';
import '../core/services/storage_service.dart';
import '../core/constants/firestore_paths.dart';
import '../core/enums/message_type.dart';
import '../core/enums/message_status.dart';
import '../models/message.dart';

class ChatViewModel extends ChangeNotifier {
  final String conversationId;
  final FirestoreService _firestoreService = FirestoreService();
  final String? _currentUserId = FirebaseAuth.instance.currentUser?.uid;
  final ScrollController scrollController = ScrollController();

  StreamSubscription? _messagesSubscription;
  Timer? _typingDebounce;
  Timer? _idleTimer;

  bool _isTyping = false;

  ChatViewModel(this.conversationId) {
    // Optional: could initialize listeners here if needed
  }

  Stream<QuerySnapshot> get messagesStream {
    return _firestoreService.getMessages(conversationId);
  }

  Stream<DocumentSnapshot> get conversationStream {
    return FirebaseFirestore.instance
        .collection('conversations')
        .doc(conversationId)
        .snapshots();
  }

  void onTextChanged(String text) {
    if (_currentUserId == null) return;

    if (_typingDebounce?.isActive ?? false) _typingDebounce!.cancel();

    if (!_isTyping && text.isNotEmpty) {
      _isTyping = true;
      _firestoreService.updateTypingStatus(
        conversationId,
        _currentUserId,
        true,
      );
    }

    if (text.isEmpty) {
      _clearTypingStatus();
      return;
    }

    _typingDebounce = Timer(const Duration(milliseconds: 1000), () {
      // Debounce logic - reset idle timer
      _idleTimer?.cancel();
      _idleTimer = Timer(const Duration(seconds: 2), () {
        _clearTypingStatus();
      });
    });
  }

  void _clearTypingStatus() {
    if (_currentUserId == null || !_isTyping) return;
    _isTyping = false;
    _firestoreService.updateTypingStatus(conversationId, _currentUserId, false);
  }

  Future<void> sendTextMessage(String text) async {
    final uid = _currentUserId;
    if (uid == null || text.trim().isEmpty) return;

    final timestamp = Timestamp.now();
    final message = Message(
      id: '', // Will be generated by Firestore
      senderId: uid,
      text: text.trim(),
      type: MessageType.text,
      reactions: {},
      status: MessageStatus.sending, // Optimistic UI
      readBy: {},
      deletedFor: [],
      deletedForEveryone: false,
      createdAt: timestamp,
    );

    try {
      _clearTypingStatus(); // Clear typing status immediately on send

      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
        conversationId,
        text.trim(),
        timestamp,
      );
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending message: $e');
    }
  }

  Future<void> sendAudioMessage(String filePath, int durationSeconds) async {
    final uid = _currentUserId;
    if (uid == null) return;

    try {
      final file = File(filePath);
      final url = await StorageService().uploadAudio(file);
      final timestamp = Timestamp.now();
      final message = Message(
        id: '',
        senderId: uid,
        type: MessageType.audio,
        mediaUrl: url,
        duration: durationSeconds,
        reactions: {},
        status: MessageStatus.sent,
        readBy: {},
        deletedFor: [],
        deletedForEveryone: false,
        createdAt: timestamp,
      );
      await _firestoreService.sendMessage(conversationId, message.toMap());
      await _firestoreService.updateConversationLastMessage(
          conversationId, '🎤 Voice message', timestamp);
      _scrollToBottom();
    } catch (e) {
      debugPrint('Error sending audio: $e');
    }
  }

  Future<void> toggleReaction(String messageId, String emoji) async {
    final uid = _currentUserId;
    if (uid == null) return;

    try {
      // We need to read the current reactions for this message to toggle properly
      final msgDoc = await FirebaseFirestore.instance
          .collection(FirestorePaths.conversations)
          .doc(conversationId)
          .collection(FirestorePaths.messages)
          .doc(messageId)
          .get();

      if (!msgDoc.exists) return;

      final reactions = Map<String, String>.from(
        msgDoc.data()?['reactions'] ?? {},
      );
      final currentReaction = reactions[uid];

      if (currentReaction == emoji) {
        // Remove reaction
        await _firestoreService.updateMessageReaction(
          conversationId,
          messageId,
          uid,
          null,
        );
      } else {
        // Add or change reaction
        await _firestoreService.updateMessageReaction(
          conversationId,
          messageId,
          uid,
          emoji,
        );
      }
    } catch (e) {
      debugPrint('Error toggling reaction: $e');
    }
  }

  void _scrollToBottom() {
    if (scrollController.hasClients) {
      scrollController.animateTo(
        0.0,
        duration: const Duration(milliseconds: 300),
        curve: Curves.easeOut,
      );
    }
  }

  @override
  void dispose() {
    _messagesSubscription?.cancel();
    _typingDebounce?.cancel();
    _idleTimer?.cancel();
    _clearTypingStatus();
    scrollController.dispose();
    super.dispose();
  }
}
